### ISSUE TITLE
Single selection search not clearing upon selection

### ISSUE THREAD

**Issue by malwar3z** [sanusart/react-dropdown-select#191]
Hi , 
I've noticed something that looks like a bug to me,
this can be reproduced within your demo example: https://sanusart.github.io/react-dropdown-select/
Every time i search for an x value within my dropdown and then select it,
whenever i re-open the dropdown i'm unable to see all the other values ,
and to make them appear again i need to search for them by typing (or by removing the current selection).

How to reproduce:
- set single selection (toggle multi)
- look for an x Name by typing (using the search functionality)
- select it
- try to open again the dropdown

It looks like the search value that was used previously doesn't get a reset and it's still applying on the 
dropdown items.

--ADDITIONAL NOTE : it seems that the bug only happens the first time i re-open the dropdown the **first** time

**Comment by DLatheron** [comment]
This is still an issue... I've been able to reproduce it as above.

*might* be related to the latest version of React 16 (16.14) because I've pretty sure we didn't have this issue before a recent upgrade (in fact I can't reproduce it on our deployed environments which are React 16.9 (but I can't still be 100% because there are a number of other confounding factors).
