### ISSUE TITLE
Two children with same key Error

### ISSUE THREAD

**Issue by meinhoonharsh** [sanusart/react-dropdown-select#221]
If we pass an array as a value, It will produces Error name `Warning: Encountered two children with same keys`

![image](https://user-images.githubusercontent.com/64343449/155614151-7fd2517e-09a1-415a-b7f8-6701864493ab.png)

#### Steps to Reproduce
-  Pass an array of objects to `options` where key `value` of any object is an array, like this
``` js
const options = [
        { label: "Albania", value: [1,2,2,3,34,4] },
        { label: "Argentina", value: 54 },
    ];

```

- Start your Server and open Console to see logs
- Click on the select and view logs

**Comment by meinhoonharsh** [comment]
@sanusart @voneiden @pattiereaves I want to work on this issue

**Comment by sanusart** [comment]
Feel free to do so

**Comment by WardenSlayer** [comment]
Any updates on this? I am running into the same erorr

**Comment by WardenSlayer** [comment]
> If we pass an array as a value, It will produces Error name `Warning: Encountered two children with same keys`
> 
> ![image](https://user-images.githubusercontent.com/64343449/155614151-7fd2517e-09a1-415a-b7f8-6701864493ab.png)
> 
> #### Steps to Reproduce
> * Pass an array of objects to `options` where key `value` of any object is an array, like this
> 
> ```js
> const options = [
>         { label: "Albania", value: [1,2,2,3,34,4] },
>         { label: "Argentina", value: 54 },
>     ];
> ```
> 
> * Start your Server and open Console to see logs
> * Click on the select and view logs

Hey, I had this same error occur and I pulled my hair out for a while. But then I figured it out.
The options keyword is looking for an array of objects [{label,value},{label,value},...etc] to be passed into it. If you just pass in the objects {} you get the duplicate key error because even though the objects contain different data, they are being treated as the same. What I did to fix my issue was to use a {label,'tag'} which I later used the tag to find the actual object as part of the "onchange" call
