### ISSUE TITLE
dropdownPosition "top" does not work with portal

### ISSUE THREAD

**Issue by Krispy3000** [sanusart/react-dropdown-select#73]
Hello, when using the `portal` option and `dropdown="auto"`, the dropdown does not appear above the select input as expected when it is at the bottom of a page. Instead it clips the the dropdown underneath the slider to fit in the window.

**Comment by Krispy3000** [comment]
Here is a cod example demonstrating the issue: https://codesandbox.io/s/zen-chebyshev-juz7e?fontsize=14&hidenavigation=1&theme=dark

**Comment by akdjr** [comment]
I was playing around with this and it seems to be due to the way the dropdown content height is calculated.  When not using portals, getting the bounding rect of the top level select ref correctly returns the height of both the select itself and the content as the content is in flow.  When using portals, the content is not a part of the top level select and as such, getting the bounding rect will return only the height of the select and not the content.

**Comment by sanusart** [comment]
Yes, there are some calculations not taking portal mode measurements into account. Definitely a bug, just had no time to deal with it. Will look into it during the weekend hopefully.

**Comment by akdjr** [comment]
I think I have a fix - I'll submit a PR!

**Comment by sanusart** [comment]
Thank you @akdjr for the fix, published version: 4.1.0
